<?php
// This file handles the admin area and functions - You can use this file to make changes to the dashboard.

/************* DASHBOARD WIDGETS *****************/
// Disable default dashboard widgets
// Remove dashboard widgets
function remove_dashboard_meta() {
		remove_meta_box( 'dashboard_incoming_links', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_plugins', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_primary', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_secondary', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_quick_press', 'dashboard', 'side' );
		remove_meta_box( 'dashboard_recent_drafts', 'dashboard', 'side' );
		remove_meta_box( 'dashboard_recent_comments', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_right_now', 'dashboard', 'normal' );
		remove_meta_box( 'dashboard_activity', 'dashboard', 'normal');
}
add_action( 'admin_init', 'remove_dashboard_meta' );

remove_action( 'welcome_panel', 'wp_welcome_panel' );

/**
 * Add a widget to the dashboard.
 *
 * This function is hooked into the 'wp_dashboard_setup' action below.
 */
function acbase_add_dashboard_widgets() {
	wp_add_dashboard_widget(
		'acbase_welcome_widget', // Widget slug.
		'Getting Started', // Title.
		'acbase_welcome_widget_function' // Display function.
	);
}
add_action( 'wp_dashboard_setup', 'acbase_add_dashboard_widgets' );

/**
 * Create the function to output the contents of your Dashboard Widget.
 */
function acbase_welcome_widget_function() {

	echo 'To change site-wide settings please visit the following pages <br />';
	echo '<ol>
					<li>
					<a class="btn" href="/wp-admin/admin.php?page=theme-general-settings">General Theme Settings</a>
					</li>
					<li>
					<a class="btn" href="/wp-admin/admin.php?page=theme-privacy-settings">Privacy Policy Settings</a>
					</li>
					<li>
					<a class="btn" href="/wp-admin/admin.php?page=theme-SEO-settings">SEO Settings</a>
					</li>
				</ol>';

}

function acbase_add_another_dashboard_widgets() {
	wp_add_dashboard_widget(
		'acbase_latest_widget', // Widget slug.
		'Latest Posts', // Title.
		'acbase_latest_widget_function' // Display function.
	);
}
add_action( 'wp_dashboard_setup', 'acbase_add_another_dashboard_widgets' );
/**
 * Create the function to output the contents of your Dashboard Widget.
 */
function acbase_latest_widget_function() {

				$lastposts = get_posts( array(
			    'posts_per_page' => 3
			) );

			if ( $lastposts ) {
				 echo '<ul>';
			    foreach ( $lastposts as $post ) :
			        setup_postdata( $post ); //print_R($post)?>
			        <li>
								<a href="<?php echo $post->guid; ?>"><?php echo $post->post_title; ?></a>
							</li>
			    <?php
			    endforeach;
			    wp_reset_postdata();
					echo '</ul>';
			}
}

function remove_from_admin_bar($wp_admin_bar) {
    /*
     * Placing items in here will only remove them from admin bar
     * when viewing the fronte end of the site
    */

        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu

        // WordPress Core Items (uncomment to remove)
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        //$wp_admin_bar->remove_node('wp-logo');
        $wp_admin_bar->remove_node('my-account');
        //$wp_admin_bar->remove_node('my-account');
        //$wp_admin_bar->remove_node('search');
        //$wp_admin_bar->remove_node('customize');


    /*
     * Items placed outside the if statement will remove it from both the frontend
     * and backend of the site
    */
    $wp_admin_bar->remove_node('wp-logo');
}
add_action('admin_bar_menu', 'remove_from_admin_bar', 999);

add_filter('contextual_help_list','contextual_help_list_remove');
function contextual_help_list_remove(){
    global $current_screen;
    $current_screen->remove_help_tabs();
}

// Custom Backend Footer
function acbase_custom_admin_footer() {
	_e('<span id="footer-thankyou">Developed by <a href="https://alastaircox.com" target="_blank">Alastair Cox</a></span>.', 'acbase');
}

// adding it to the admin area
add_filter('admin_footer_text', 'acbase_custom_admin_footer');


/**
* Disable the emoji's
*/
function disable_emojis() {
	remove_action( 'wp_head', 'print_emoji_detection_script', 7 );
	remove_action( 'admin_print_scripts', 'print_emoji_detection_script' );
	remove_action( 'wp_print_styles', 'print_emoji_styles' );
	remove_action( 'admin_print_styles', 'print_emoji_styles' );
	remove_filter( 'the_content_feed', 'wp_staticize_emoji' );
	remove_filter( 'comment_text_rss', 'wp_staticize_emoji' );
	remove_filter( 'wp_mail', 'wp_staticize_emoji_for_email' );
	add_filter( 'tiny_mce_plugins', 'disable_emojis_tinymce' );
	add_filter( 'wp_resource_hints', 'disable_emojis_remove_dns_prefetch', 10, 2 );
}

add_action( 'init', 'disable_emojis' );

/**
* Filter function used to remove the tinymce emoji plugin.
*
* @param array $plugins
* @return array Difference betwen the two arrays
*/
function disable_emojis_tinymce( $plugins ) {
	if ( is_array( $plugins ) ) {
	return array_diff( $plugins, array( 'wpemoji' ) );
	} else {
	return array();
	}
}

/**
* Remove emoji CDN hostname from DNS prefetching hints.
*
* @param array $urls URLs to print for resource hints.
* @param string $relation_type The relation type the URLs are printed for.
* @return array Difference betwen the two arrays.
*/
function disable_emojis_remove_dns_prefetch( $urls, $relation_type ) {
	if ( 'dns-prefetch' == $relation_type ) {
	/** This filter is documented in wp-includes/formatting.php */
	$emoji_svg_url = apply_filters( 'emoji_svg_url', 'https://s.w.org/images/core/emoji/2/svg/' );
	$urls = array_diff( $urls, array( $emoji_svg_url ) );
	}

	return $urls;
}


function my_acf_init() {
	$api_key = get_field('api_key', 'option');
	acf_update_setting('google_api_key', $api_key);
}
add_action('acf/init', 'my_acf_init');


function my_acf_google_map_api( $api ){

	$api['key'] = get_field('api_key', 'option');

	return $api;

}

add_filter('acf/fields/google_map/api', 'my_acf_google_map_api');


if( function_exists('acf_add_options_page') ) {

	acf_add_options_page(array(
		'page_title' 	=> 'Options',
		'menu_title'	=> 'Options',
		'menu_slug' 	=> 'theme-general-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false,
		'icon_url' => '',
		'update_button' => __('Update Settings', 'acf'),
	));

	acf_add_options_page(array(
		'page_title' 	=> 'Privacy Settings',
		'menu_title'	=> 'Privacy',
		'menu_slug' 	=> 'theme-privacy-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false,
		'icon_url' => 'dashicons-admin-network',
		'update_button' => __('Update Privacy Settings', 'acf'),
	));

	acf_add_options_page(array(
		'page_title' 	=> 'SEO Settings',
		'menu_title'	=> 'SEO',
		'menu_slug' 	=> 'theme-SEO-settings',
		'capability'	=> 'edit_posts',
		'redirect'		=> false,
		'icon_url' => 'dashicons-megaphone',
		'update_button' => __('Update SEO Settings', 'acf'),
	));

}

add_action('admin_head', 'my_admin_style');

function my_admin_style() {
  echo '<style>
			.acf-postbox h2 {
		background: #ffca28;
		}
  </style>';
}
